# Generated by Django 3.2.9 on 2021-12-06 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coach", models.CharField(blank=True, max_length=50)),
                ("student", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(blank=True, max_length=256)),
                ("note_id", models.CharField(blank=True, max_length=256)),
                ("content", models.TextField(blank=True)),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ended_time", models.DateTimeField(null=True)),
            ],
        ),
    ]
