# Generated by Django 3.2.9 on 2021-12-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_alter_meeting_ended_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='content',
            new_name='coach_content',
        ),
        migrations.AddField(
            model_name='meeting',
            name='coach_audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='student_audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='student_content',
            field=models.TextField(blank=True),
        ),
    ]
