# Generated by Django 3.2.9 on 2021-12-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20211206_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='note_id',
            new_name='meeting_id',
        ),
    ]
