# Generated by Django 3.2.9 on 2021-12-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_rename_note_id_meeting_meeting_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='coach_audio',
            new_name='audio_file',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='coach_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='student_audio',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='student_content',
        ),
    ]
