# Generated by Django 3.2.9 on 2021-12-06 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0005_auto_20211206_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMeeting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('coach', models.CharField(blank=True, max_length=50)),
                ('student', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('meeting_id', models.CharField(blank=True, max_length=256)),
                ('audio_file', models.TextField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_time', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical meeting',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
