# Generated by Django 3.2.9 on 2021-12-07 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_historicalmeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmeeting',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='audio_file',
        ),
    ]
